//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace aixm.v5_1_1
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AbstractSegmentPointType", Namespace="http://www.aixm.aero/schema/5.1.1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("AbstractSegmentPoint", Namespace="http://www.aixm.aero/schema/5.1.1")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AerialRefuellingPointType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EnRouteSegmentPointType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TerminalSegmentPointType))]
    public partial class AbstractSegmentPointType : aixm.v5_1_1.AbstractAIXMObjectType
    {
    }
}
