//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace aixm.v5_1_1
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AbstractSegmentLegType", Namespace="http://www.aixm.aero/schema/5.1.1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("AbstractSegmentLeg", Namespace="http://www.aixm.aero/schema/5.1.1")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractApproachLegType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(aero.aixm.schema._5_1_1.extensions.eur.adr.ApproachLegType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArrivalFeederLegType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArrivalLegType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DepartureLegType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FinalLegType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InitialLegType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntermediateLegType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MissedApproachLegType))]
    public abstract partial class AbstractSegmentLegType : aixm.v5_1_1.AbstractAIXMFeatureType
    {
    }
}
