//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace aixm.v5_1_1
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AbstractServiceType", Namespace="http://www.aixm.aero/schema/5.1.1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("AbstractService", Namespace="http://www.aixm.aero/schema/5.1.1")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractAirportGroundServiceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractTrafficSeparationServiceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AircraftGroundServiceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AirportClearanceServiceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AirportSuppliesServiceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AirTrafficControlServiceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AirTrafficManagementServiceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FireFightingServiceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GroundTrafficControlServiceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InformationServiceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PassengerServiceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SearchRescueServiceType))]
    public abstract partial class AbstractServiceType : aixm.v5_1_1.AbstractAIXMFeatureType
    {
    }
}
