//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace aixm.v5_1_1
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AirspaceVolumeType", Namespace="http://www.aixm.aero/schema/5.1.1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("AirspaceVolume", Namespace="http://www.aixm.aero/schema/5.1.1")]
    public partial class AirspaceVolumeType : aixm.v5_1_1.AbstractAIXMObjectType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("upperLimit", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceVerticalType UpperLimit { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("upperLimitReference", IsNullable=true)]
        public aixm.v5_1_1.CodeVerticalReferenceType UpperLimitReference { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("maximumLimit", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceVerticalType MaximumLimit { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("maximumLimitReference", IsNullable=true)]
        public aixm.v5_1_1.CodeVerticalReferenceType MaximumLimitReference { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("lowerLimit", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceVerticalType LowerLimit { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("lowerLimitReference", IsNullable=true)]
        public aixm.v5_1_1.CodeVerticalReferenceType LowerLimitReference { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("minimumLimit", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceVerticalType MinimumLimit { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("minimumLimitReference", IsNullable=true)]
        public aixm.v5_1_1.CodeVerticalReferenceType MinimumLimitReference { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("width", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceType Width { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("horizontalProjection", IsNullable=true)]
        public SurfacePropertyType HorizontalProjection { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("centreline", IsNullable=true)]
        public CurvePropertyType Centreline { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("contributorAirspace", IsNullable=true)]
        public AirspaceVolumeDependencyPropertyType ContributorAirspace { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<NotePropertyType> _annotation;
        
        [System.Xml.Serialization.XmlElementAttribute("annotation", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<NotePropertyType> Annotation
        {
            get
            {
                return this._annotation;
            }
            private set
            {
                this._annotation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Annotation-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Annotation collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnnotationSpecified
        {
            get
            {
                return (this.Annotation.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="AirspaceVolumeType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="AirspaceVolumeType" /> class.</para>
        /// </summary>
        public AirspaceVolumeType()
        {
            this._annotation = new System.Collections.ObjectModel.Collection<NotePropertyType>();
            this._extension = new System.Collections.ObjectModel.Collection<AirspaceVolumeTypeExtension>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AirspaceVolumeTypeExtension> _extension;
        
        [System.Xml.Serialization.XmlElementAttribute("extension")]
        public System.Collections.ObjectModel.Collection<AirspaceVolumeTypeExtension> Extension
        {
            get
            {
                return this._extension;
            }
            private set
            {
                this._extension = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Extension-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Extension collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtensionSpecified
        {
            get
            {
                return (this.Extension.Count != 0);
            }
        }
    }
}
