//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace aixm.v5_1_1
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DistanceIndicationTimeSliceType", Namespace="http://www.aixm.aero/schema/5.1.1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("DistanceIndicationTimeSlice", Namespace="http://www.aixm.aero/schema/5.1.1")]
    public partial class DistanceIndicationTimeSliceType : aixm.v5_1_1.AbstractAIXMTimeSliceType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("distance", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceType Distance { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("minimumReceptionAltitude", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceVerticalType MinimumReceptionAltitude { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("type", IsNullable=true)]
        public aixm.v5_1_1.CodeDistanceIndicationType Type { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("fix", IsNullable=true)]
        public DesignatedPointPropertyType Fix { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("pointChoice_fixDesignatedPoint", IsNullable=true)]
        public DesignatedPointPropertyType PointChoice_FixDesignatedPoint { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("pointChoice_navaidSystem", IsNullable=true)]
        public NavaidPropertyType PointChoice_NavaidSystem { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("pointChoice_position", IsNullable=true)]
        public PointPropertyType PointChoice_Position { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("pointChoice_runwayPoint", IsNullable=true)]
        public RunwayCentrelinePointPropertyType PointChoice_RunwayPoint { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("pointChoice_aimingPoint", IsNullable=true)]
        public TouchDownLiftOffPropertyType PointChoice_AimingPoint { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("pointChoice_airportReferencePoint", IsNullable=true)]
        public AirportHeliportPropertyType PointChoice_AirportReferencePoint { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<NotePropertyType> _annotation;
        
        [System.Xml.Serialization.XmlElementAttribute("annotation", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<NotePropertyType> Annotation
        {
            get
            {
                return this._annotation;
            }
            private set
            {
                this._annotation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Annotation-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Annotation collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnnotationSpecified
        {
            get
            {
                return (this.Annotation.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="DistanceIndicationTimeSliceType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="DistanceIndicationTimeSliceType" /> class.</para>
        /// </summary>
        public DistanceIndicationTimeSliceType()
        {
            this._annotation = new System.Collections.ObjectModel.Collection<NotePropertyType>();
            this._extension = new System.Collections.ObjectModel.Collection<DistanceIndicationTimeSliceTypeExtension>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<DistanceIndicationTimeSliceTypeExtension> _extension;
        
        [System.Xml.Serialization.XmlElementAttribute("extension")]
        public System.Collections.ObjectModel.Collection<DistanceIndicationTimeSliceTypeExtension> Extension
        {
            get
            {
                return this._extension;
            }
            private set
            {
                this._extension = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Extension-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Extension collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtensionSpecified
        {
            get
            {
                return (this.Extension.Count != 0);
            }
        }
    }
}
