//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace aixm.v5_1_1
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ElevatedPointType", Namespace="http://www.aixm.aero/schema/5.1.1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ElevatedPoint", Namespace="http://www.aixm.aero/schema/5.1.1")]
    public partial class ElevatedPointType : PointType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("elevation", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceVerticalType Elevation { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("geoidUndulation", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceSignedType GeoidUndulation { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("verticalDatum", IsNullable=true)]
        public aixm.v5_1_1.CodeVerticalDatumType VerticalDatum { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("verticalAccuracy", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceType VerticalAccuracy { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ElevatedPointTypeExtension> _extension;
        
        [System.Xml.Serialization.XmlElementAttribute("extension")]
        public System.Collections.ObjectModel.Collection<ElevatedPointTypeExtension> Extension
        {
            get
            {
                return this._extension;
            }
            private set
            {
                this._extension = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Extension-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Extension collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtensionSpecified
        {
            get
            {
                return (this.Extension.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="ElevatedPointType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ElevatedPointType" /> class.</para>
        /// </summary>
        public ElevatedPointType()
        {
            this._extension = new System.Collections.ObjectModel.Collection<ElevatedPointTypeExtension>();
        }
    }
}
