//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace aixm.v5_1_1
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("HoldingPatternTimeSliceType", Namespace="http://www.aixm.aero/schema/5.1.1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("HoldingPatternTimeSlice", Namespace="http://www.aixm.aero/schema/5.1.1")]
    public partial class HoldingPatternTimeSliceType : aixm.v5_1_1.AbstractAIXMTimeSliceType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("type", IsNullable=true)]
        public aixm.v5_1_1.CodeHoldingUsageType Type { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("outboundCourse", IsNullable=true)]
        public aixm.v5_1_1.ValBearingType OutboundCourse { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("outboundCourseType", IsNullable=true)]
        public aixm.v5_1_1.CodeCourseType OutboundCourseType { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("inboundCourse", IsNullable=true)]
        public aixm.v5_1_1.ValBearingType InboundCourse { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("turnDirection", IsNullable=true)]
        public aixm.v5_1_1.CodeDirectionTurnType TurnDirection { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("upperLimit", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceVerticalType UpperLimit { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("upperLimitReference", IsNullable=true)]
        public aixm.v5_1_1.CodeVerticalReferenceType UpperLimitReference { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("lowerLimit", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceVerticalType LowerLimit { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("lowerLimitReference", IsNullable=true)]
        public aixm.v5_1_1.CodeVerticalReferenceType LowerLimitReference { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("speedLimit", IsNullable=true)]
        public aixm.v5_1_1.ValSpeedType SpeedLimit { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("instruction", IsNullable=true)]
        public aixm.v5_1_1.TextInstructionType Instruction { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("nonStandardHolding", IsNullable=true)]
        public aixm.v5_1_1.CodeYesNoType NonStandardHolding { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("outboundLegSpan_endPoint", IsNullable=true)]
        public SegmentPointPropertyType OutboundLegSpan_EndPoint { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("outboundLegSpan_endDistance", IsNullable=true)]
        public HoldingPatternDistancePropertyType OutboundLegSpan_EndDistance { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("outboundLegSpan_endTime", IsNullable=true)]
        public HoldingPatternDurationPropertyType OutboundLegSpan_EndTime { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("holdingPoint", IsNullable=true)]
        public SegmentPointPropertyType HoldingPoint { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("extent", IsNullable=true)]
        public CurvePropertyType Extent { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<NotePropertyType> _annotation;
        
        [System.Xml.Serialization.XmlElementAttribute("annotation", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<NotePropertyType> Annotation
        {
            get
            {
                return this._annotation;
            }
            private set
            {
                this._annotation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Annotation-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Annotation collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnnotationSpecified
        {
            get
            {
                return (this.Annotation.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="HoldingPatternTimeSliceType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="HoldingPatternTimeSliceType" /> class.</para>
        /// </summary>
        public HoldingPatternTimeSliceType()
        {
            this._annotation = new System.Collections.ObjectModel.Collection<NotePropertyType>();
            this._extension = new System.Collections.ObjectModel.Collection<HoldingPatternTimeSliceTypeExtension>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<HoldingPatternTimeSliceTypeExtension> _extension;
        
        [System.Xml.Serialization.XmlElementAttribute("extension")]
        public System.Collections.ObjectModel.Collection<HoldingPatternTimeSliceTypeExtension> Extension
        {
            get
            {
                return this._extension;
            }
            private set
            {
                this._extension = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Extension-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Extension collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtensionSpecified
        {
            get
            {
                return (this.Extension.Count != 0);
            }
        }
    }
}
