//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace aixm.v5_1_1
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("NoteType", Namespace="http://www.aixm.aero/schema/5.1.1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Note", Namespace="http://www.aixm.aero/schema/5.1.1")]
    public partial class NoteType : aixm.v5_1_1.AbstractAIXMObjectType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("propertyName", IsNullable=true)]
        public aixm.v5_1_1.TextPropertyNameType PropertyName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("purpose", IsNullable=true)]
        public aixm.v5_1_1.CodeNotePurposeType Purpose { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<LinguisticNotePropertyType> _translatedNote;
        
        [System.Xml.Serialization.XmlElementAttribute("translatedNote", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<LinguisticNotePropertyType> TranslatedNote
        {
            get
            {
                return this._translatedNote;
            }
            private set
            {
                this._translatedNote = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die TranslatedNote-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the TranslatedNote collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TranslatedNoteSpecified
        {
            get
            {
                return (this.TranslatedNote.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="NoteType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="NoteType" /> class.</para>
        /// </summary>
        public NoteType()
        {
            this._translatedNote = new System.Collections.ObjectModel.Collection<LinguisticNotePropertyType>();
            this._extension = new System.Collections.ObjectModel.Collection<NoteTypeExtension>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<NoteTypeExtension> _extension;
        
        [System.Xml.Serialization.XmlElementAttribute("extension")]
        public System.Collections.ObjectModel.Collection<NoteTypeExtension> Extension
        {
            get
            {
                return this._extension;
            }
            private set
            {
                this._extension = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Extension-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Extension collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtensionSpecified
        {
            get
            {
                return (this.Extension.Count != 0);
            }
        }
    }
}
