//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace aixm.v5_1_1
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PrimarySurveillanceRadarTimeSliceType", Namespace="http://www.aixm.aero/schema/5.1.1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("PrimarySurveillanceRadarTimeSlice", Namespace="http://www.aixm.aero/schema/5.1.1")]
    public partial class PrimarySurveillanceRadarTimeSliceType : aixm.v5_1_1.AbstractAIXMTimeSliceType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("name", IsNullable=true)]
        public aixm.v5_1_1.TextNameType Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("serialNumber", IsNullable=true)]
        public aixm.v5_1_1.TextDesignatorType SerialNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("range", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceType Range { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("rangeAccuracy", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceType RangeAccuracy { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("dualChannel", IsNullable=true)]
        public aixm.v5_1_1.CodeYesNoType DualChannel { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("movingTargetIndicator", IsNullable=true)]
        public aixm.v5_1_1.CodeYesNoType MovingTargetIndicator { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("standbyPower", IsNullable=true)]
        public aixm.v5_1_1.CodeStandbyPowerType StandbyPower { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("digital", IsNullable=true)]
        public aixm.v5_1_1.CodeYesNoType Digital { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("militaryUseOnly", IsNullable=true)]
        public aixm.v5_1_1.CodeYesNoType MilitaryUseOnly { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("specialUseOnly", IsNullable=true)]
        public aixm.v5_1_1.CodeYesNoType SpecialUseOnly { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("specialAircraftOnly", IsNullable=true)]
        public aixm.v5_1_1.CodeYesNoType SpecialAircraftOnly { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("magneticVariation", IsNullable=true)]
        public aixm.v5_1_1.ValMagneticVariationType MagneticVariation { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("magneticVariationAccuracy", IsNullable=true)]
        public aixm.v5_1_1.ValAngleType MagneticVariationAccuracy { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("dateMagneticVariation", IsNullable=true)]
        public aixm.v5_1_1.DateYearType DateMagneticVariation { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ContactInformationPropertyType> _contact;
        
        [System.Xml.Serialization.XmlElementAttribute("contact", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<ContactInformationPropertyType> Contact
        {
            get
            {
                return this._contact;
            }
            private set
            {
                this._contact = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Contact-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Contact collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ContactSpecified
        {
            get
            {
                return (this.Contact.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="PrimarySurveillanceRadarTimeSliceType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PrimarySurveillanceRadarTimeSliceType" /> class.</para>
        /// </summary>
        public PrimarySurveillanceRadarTimeSliceType()
        {
            this._contact = new System.Collections.ObjectModel.Collection<ContactInformationPropertyType>();
            this._annotation = new System.Collections.ObjectModel.Collection<NotePropertyType>();
            this._groundStation = new System.Collections.ObjectModel.Collection<SurveillanceGroundStationPropertyType>();
            this._extension = new System.Collections.ObjectModel.Collection<PrimarySurveillanceRadarTimeSliceTypeExtension>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("location", IsNullable=true)]
        public ElevatedPointPropertyType Location { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<NotePropertyType> _annotation;
        
        [System.Xml.Serialization.XmlElementAttribute("annotation", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<NotePropertyType> Annotation
        {
            get
            {
                return this._annotation;
            }
            private set
            {
                this._annotation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Annotation-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Annotation collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnnotationSpecified
        {
            get
            {
                return (this.Annotation.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("verticalCoverageAltitude", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceVerticalType VerticalCoverageAltitude { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("verticalCoverageDistance", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceType VerticalCoverageDistance { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("verticalCoverageAzimuth", IsNullable=true)]
        public aixm.v5_1_1.ValBearingType VerticalCoverageAzimuth { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("antennaTiltFixed", IsNullable=true)]
        public aixm.v5_1_1.CodeYesNoType AntennaTiltFixed { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("tiltAngle", IsNullable=true)]
        public aixm.v5_1_1.ValAngleType TiltAngle { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("automatedRadarTerminalSystem", IsNullable=true)]
        public aixm.v5_1_1.TextDesignatorType AutomatedRadarTerminalSystem { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<SurveillanceGroundStationPropertyType> _groundStation;
        
        [System.Xml.Serialization.XmlElementAttribute("groundStation", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<SurveillanceGroundStationPropertyType> GroundStation
        {
            get
            {
                return this._groundStation;
            }
            private set
            {
                this._groundStation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die GroundStation-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the GroundStation collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GroundStationSpecified
        {
            get
            {
                return (this.GroundStation.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("type", IsNullable=true)]
        public aixm.v5_1_1.CodePrimaryRadarType Type { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PrimarySurveillanceRadarTimeSliceTypeExtension> _extension;
        
        [System.Xml.Serialization.XmlElementAttribute("extension")]
        public System.Collections.ObjectModel.Collection<PrimarySurveillanceRadarTimeSliceTypeExtension> Extension
        {
            get
            {
                return this._extension;
            }
            private set
            {
                this._extension = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Extension-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Extension collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtensionSpecified
        {
            get
            {
                return (this.Extension.Count != 0);
            }
        }
    }
}
