//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace aixm.v5_1_1
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RadioCommunicationChannelTimeSliceType", Namespace="http://www.aixm.aero/schema/5.1.1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("RadioCommunicationChannelTimeSlice", Namespace="http://www.aixm.aero/schema/5.1.1")]
    public partial class RadioCommunicationChannelTimeSliceType : aixm.v5_1_1.AbstractAIXMTimeSliceType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("mode", IsNullable=true)]
        public aixm.v5_1_1.CodeCommunicationModeType Mode { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("rank", IsNullable=true)]
        public aixm.v5_1_1.CodeFacilityRankingType Rank { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("frequencyTransmission", IsNullable=true)]
        public aixm.v5_1_1.ValFrequencyType FrequencyTransmission { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("frequencyReception", IsNullable=true)]
        public aixm.v5_1_1.ValFrequencyType FrequencyReception { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("channel", IsNullable=true)]
        public aixm.v5_1_1.CodeCommunicationChannelType Channel { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("logon", IsNullable=true)]
        public aixm.v5_1_1.TextDesignatorType Logon { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("emissionType", IsNullable=true)]
        public aixm.v5_1_1.CodeRadioEmissionType EmissionType { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("selectiveCall", IsNullable=true)]
        public aixm.v5_1_1.CodeYesNoType SelectiveCall { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("flightChecked", IsNullable=true)]
        public aixm.v5_1_1.CodeYesNoType FlightChecked { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("trafficDirection", IsNullable=true)]
        public aixm.v5_1_1.CodeCommunicationDirectionType TrafficDirection { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ElevatedPointPropertyType> _location;
        
        [System.Xml.Serialization.XmlElementAttribute("location", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<ElevatedPointPropertyType> Location
        {
            get
            {
                return this._location;
            }
            private set
            {
                this._location = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Location-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Location collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LocationSpecified
        {
            get
            {
                return (this.Location.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="RadioCommunicationChannelTimeSliceType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="RadioCommunicationChannelTimeSliceType" /> class.</para>
        /// </summary>
        public RadioCommunicationChannelTimeSliceType()
        {
            this._location = new System.Collections.ObjectModel.Collection<ElevatedPointPropertyType>();
            this._availability = new System.Collections.ObjectModel.Collection<RadioCommunicationOperationalStatusPropertyType>();
            this._annotation = new System.Collections.ObjectModel.Collection<NotePropertyType>();
            this._extension = new System.Collections.ObjectModel.Collection<RadioCommunicationChannelTimeSliceTypeExtension>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RadioCommunicationOperationalStatusPropertyType> _availability;
        
        [System.Xml.Serialization.XmlElementAttribute("availability", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<RadioCommunicationOperationalStatusPropertyType> Availability
        {
            get
            {
                return this._availability;
            }
            private set
            {
                this._availability = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Availability-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Availability collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AvailabilitySpecified
        {
            get
            {
                return (this.Availability.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<NotePropertyType> _annotation;
        
        [System.Xml.Serialization.XmlElementAttribute("annotation", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<NotePropertyType> Annotation
        {
            get
            {
                return this._annotation;
            }
            private set
            {
                this._annotation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Annotation-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Annotation collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnnotationSpecified
        {
            get
            {
                return (this.Annotation.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RadioCommunicationChannelTimeSliceTypeExtension> _extension;
        
        [System.Xml.Serialization.XmlElementAttribute("extension")]
        public System.Collections.ObjectModel.Collection<RadioCommunicationChannelTimeSliceTypeExtension> Extension
        {
            get
            {
                return this._extension;
            }
            private set
            {
                this._extension = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Extension-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Extension collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtensionSpecified
        {
            get
            {
                return (this.Extension.Count != 0);
            }
        }
    }
}
