//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace aixm.v5_1_1
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RouteSegmentTimeSliceType", Namespace="http://www.aixm.aero/schema/5.1.1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("RouteSegmentTimeSlice", Namespace="http://www.aixm.aero/schema/5.1.1")]
    public partial class RouteSegmentTimeSliceType : aixm.v5_1_1.AbstractAIXMTimeSliceType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("level", IsNullable=true)]
        public aixm.v5_1_1.CodeLevelType Level { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("upperLimit", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceVerticalType UpperLimit { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("upperLimitReference", IsNullable=true)]
        public aixm.v5_1_1.CodeVerticalReferenceType UpperLimitReference { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("lowerLimit", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceVerticalType LowerLimit { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("lowerLimitReference", IsNullable=true)]
        public aixm.v5_1_1.CodeVerticalReferenceType LowerLimitReference { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("minimumObstacleClearanceAltitude", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceVerticalType MinimumObstacleClearanceAltitude { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("pathType", IsNullable=true)]
        public aixm.v5_1_1.CodeRouteSegmentPathType PathType { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("trueTrack", IsNullable=true)]
        public aixm.v5_1_1.ValBearingType TrueTrack { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("magneticTrack", IsNullable=true)]
        public aixm.v5_1_1.ValBearingType MagneticTrack { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("reverseTrueTrack", IsNullable=true)]
        public aixm.v5_1_1.ValBearingType ReverseTrueTrack { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("reverseMagneticTrack", IsNullable=true)]
        public aixm.v5_1_1.ValBearingType ReverseMagneticTrack { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("length", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceType Length { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("widthLeft", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceType WidthLeft { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("widthRight", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceType WidthRight { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("turnDirection", IsNullable=true)]
        public aixm.v5_1_1.CodeDirectionTurnType TurnDirection { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("signalGap", IsNullable=true)]
        public aixm.v5_1_1.CodeYesNoType SignalGap { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("minimumEnrouteAltitude", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceVerticalType MinimumEnrouteAltitude { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("minimumCrossingAtEnd", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceVerticalType MinimumCrossingAtEnd { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("minimumCrossingAtEndReference", IsNullable=true)]
        public aixm.v5_1_1.CodeVerticalReferenceType MinimumCrossingAtEndReference { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("maximumCrossingAtEnd", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceVerticalType MaximumCrossingAtEnd { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("maximumCrossingAtEndReference", IsNullable=true)]
        public aixm.v5_1_1.CodeVerticalReferenceType MaximumCrossingAtEndReference { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("navigationType", IsNullable=true)]
        public aixm.v5_1_1.CodeRouteNavigationType NavigationType { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("requiredNavigationPerformance", IsNullable=true)]
        public aixm.v5_1_1.CodeRNPType RequiredNavigationPerformance { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("designatorSuffix", IsNullable=true)]
        public aixm.v5_1_1.CodeRouteDesignatorSuffixType DesignatorSuffix { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("start", IsNullable=true)]
        public EnRouteSegmentPointPropertyType Start { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("routeFormed", IsNullable=true)]
        public RoutePropertyType RouteFormed { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("evaluationArea", IsNullable=true)]
        public ObstacleAssessmentAreaPropertyType EvaluationArea { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("curveExtent", IsNullable=true)]
        public CurvePropertyType CurveExtent { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("end", IsNullable=true)]
        public EnRouteSegmentPointPropertyType End { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RouteAvailabilityPropertyType> _availability;
        
        [System.Xml.Serialization.XmlElementAttribute("availability", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<RouteAvailabilityPropertyType> Availability
        {
            get
            {
                return this._availability;
            }
            private set
            {
                this._availability = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Availability-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Availability collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AvailabilitySpecified
        {
            get
            {
                return (this.Availability.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="RouteSegmentTimeSliceType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="RouteSegmentTimeSliceType" /> class.</para>
        /// </summary>
        public RouteSegmentTimeSliceType()
        {
            this._availability = new System.Collections.ObjectModel.Collection<RouteAvailabilityPropertyType>();
            this._annotation = new System.Collections.ObjectModel.Collection<NotePropertyType>();
            this._extension = new System.Collections.ObjectModel.Collection<RouteSegmentTimeSliceTypeExtension>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<NotePropertyType> _annotation;
        
        [System.Xml.Serialization.XmlElementAttribute("annotation", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<NotePropertyType> Annotation
        {
            get
            {
                return this._annotation;
            }
            private set
            {
                this._annotation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Annotation-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Annotation collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnnotationSpecified
        {
            get
            {
                return (this.Annotation.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RouteSegmentTimeSliceTypeExtension> _extension;
        
        [System.Xml.Serialization.XmlElementAttribute("extension")]
        public System.Collections.ObjectModel.Collection<RouteSegmentTimeSliceTypeExtension> Extension
        {
            get
            {
                return this._extension;
            }
            private set
            {
                this._extension = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Extension-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Extension collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtensionSpecified
        {
            get
            {
                return (this.Extension.Count != 0);
            }
        }
    }
}
