//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace aixm.v5_1_1
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RunwayCentrelinePointTimeSliceType", Namespace="http://www.aixm.aero/schema/5.1.1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("RunwayCentrelinePointTimeSlice", Namespace="http://www.aixm.aero/schema/5.1.1")]
    public partial class RunwayCentrelinePointTimeSliceType : aixm.v5_1_1.AbstractAIXMTimeSliceType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("role", IsNullable=true)]
        public aixm.v5_1_1.CodeRunwayPointRoleType Role { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("designator", IsNullable=true)]
        public aixm.v5_1_1.TextDesignatorType Designator { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("location", IsNullable=true)]
        public ElevatedPointPropertyType Location { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("onRunway", IsNullable=true)]
        public RunwayDirectionPropertyType OnRunway { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RunwayDeclaredDistancePropertyType> _associatedDeclaredDistance;
        
        [System.Xml.Serialization.XmlElementAttribute("associatedDeclaredDistance", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<RunwayDeclaredDistancePropertyType> AssociatedDeclaredDistance
        {
            get
            {
                return this._associatedDeclaredDistance;
            }
            private set
            {
                this._associatedDeclaredDistance = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die AssociatedDeclaredDistance-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the AssociatedDeclaredDistance collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AssociatedDeclaredDistanceSpecified
        {
            get
            {
                return (this.AssociatedDeclaredDistance.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="RunwayCentrelinePointTimeSliceType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="RunwayCentrelinePointTimeSliceType" /> class.</para>
        /// </summary>
        public RunwayCentrelinePointTimeSliceType()
        {
            this._associatedDeclaredDistance = new System.Collections.ObjectModel.Collection<RunwayDeclaredDistancePropertyType>();
            this._navaidEquipment = new System.Collections.ObjectModel.Collection<NavaidEquipmentDistancePropertyType>();
            this._annotation = new System.Collections.ObjectModel.Collection<NotePropertyType>();
            this._extension = new System.Collections.ObjectModel.Collection<RunwayCentrelinePointTimeSliceTypeExtension>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<NavaidEquipmentDistancePropertyType> _navaidEquipment;
        
        [System.Xml.Serialization.XmlElementAttribute("navaidEquipment", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<NavaidEquipmentDistancePropertyType> NavaidEquipment
        {
            get
            {
                return this._navaidEquipment;
            }
            private set
            {
                this._navaidEquipment = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die NavaidEquipment-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the NavaidEquipment collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NavaidEquipmentSpecified
        {
            get
            {
                return (this.NavaidEquipment.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<NotePropertyType> _annotation;
        
        [System.Xml.Serialization.XmlElementAttribute("annotation", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<NotePropertyType> Annotation
        {
            get
            {
                return this._annotation;
            }
            private set
            {
                this._annotation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Annotation-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Annotation collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnnotationSpecified
        {
            get
            {
                return (this.Annotation.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RunwayCentrelinePointTimeSliceTypeExtension> _extension;
        
        [System.Xml.Serialization.XmlElementAttribute("extension")]
        public System.Collections.ObjectModel.Collection<RunwayCentrelinePointTimeSliceTypeExtension> Extension
        {
            get
            {
                return this._extension;
            }
            private set
            {
                this._extension = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Extension-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Extension collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtensionSpecified
        {
            get
            {
                return (this.Extension.Count != 0);
            }
        }
    }
}
