//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace aixm.v5_1_1
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RunwayTimeSliceType", Namespace="http://www.aixm.aero/schema/5.1.1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("RunwayTimeSlice", Namespace="http://www.aixm.aero/schema/5.1.1")]
    public partial class RunwayTimeSliceType : aixm.v5_1_1.AbstractAIXMTimeSliceType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("designator", IsNullable=true)]
        public aixm.v5_1_1.TextDesignatorType Designator { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("type", IsNullable=true)]
        public aixm.v5_1_1.CodeRunwayType Type { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("nominalLength", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceType NominalLength { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("lengthAccuracy", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceType LengthAccuracy { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("nominalWidth", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceType NominalWidth { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("widthAccuracy", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceType WidthAccuracy { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("widthShoulder", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceType WidthShoulder { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("lengthStrip", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceType LengthStrip { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("widthStrip", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceType WidthStrip { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("lengthOffset", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceSignedType LengthOffset { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("widthOffset", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceSignedType WidthOffset { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("abandoned", IsNullable=true)]
        public aixm.v5_1_1.CodeYesNoType Abandoned { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("surfaceProperties", IsNullable=true)]
        public SurfaceCharacteristicsPropertyType SurfaceProperties { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("associatedAirportHeliport", IsNullable=true)]
        public AirportHeliportPropertyType AssociatedAirportHeliport { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RunwayContaminationPropertyType> _overallContaminant;
        
        [System.Xml.Serialization.XmlElementAttribute("overallContaminant", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<RunwayContaminationPropertyType> OverallContaminant
        {
            get
            {
                return this._overallContaminant;
            }
            private set
            {
                this._overallContaminant = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die OverallContaminant-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the OverallContaminant collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OverallContaminantSpecified
        {
            get
            {
                return (this.OverallContaminant.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="RunwayTimeSliceType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="RunwayTimeSliceType" /> class.</para>
        /// </summary>
        public RunwayTimeSliceType()
        {
            this._overallContaminant = new System.Collections.ObjectModel.Collection<RunwayContaminationPropertyType>();
            this._annotation = new System.Collections.ObjectModel.Collection<NotePropertyType>();
            this._areaContaminant = new System.Collections.ObjectModel.Collection<RunwaySectionContaminationPropertyType>();
            this._extension = new System.Collections.ObjectModel.Collection<RunwayTimeSliceTypeExtension>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<NotePropertyType> _annotation;
        
        [System.Xml.Serialization.XmlElementAttribute("annotation", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<NotePropertyType> Annotation
        {
            get
            {
                return this._annotation;
            }
            private set
            {
                this._annotation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Annotation-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Annotation collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnnotationSpecified
        {
            get
            {
                return (this.Annotation.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RunwaySectionContaminationPropertyType> _areaContaminant;
        
        [System.Xml.Serialization.XmlElementAttribute("areaContaminant", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<RunwaySectionContaminationPropertyType> AreaContaminant
        {
            get
            {
                return this._areaContaminant;
            }
            private set
            {
                this._areaContaminant = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die AreaContaminant-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the AreaContaminant collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AreaContaminantSpecified
        {
            get
            {
                return (this.AreaContaminant.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RunwayTimeSliceTypeExtension> _extension;
        
        [System.Xml.Serialization.XmlElementAttribute("extension")]
        public System.Collections.ObjectModel.Collection<RunwayTimeSliceTypeExtension> Extension
        {
            get
            {
                return this._extension;
            }
            private set
            {
                this._extension = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Extension-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Extension collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtensionSpecified
        {
            get
            {
                return (this.Extension.Count != 0);
            }
        }
    }
}
