//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace aixm.v5_1_1
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RunwayProtectAreaTimeSliceType", Namespace="http://www.aixm.aero/schema/5.1.1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("RunwayProtectAreaTimeSlice", Namespace="http://www.aixm.aero/schema/5.1.1")]
    public partial class RunwayProtectAreaTimeSliceType : aixm.v5_1_1.AbstractAIXMTimeSliceType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("width", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceType Width { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("length", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceType Length { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("lighting", IsNullable=true)]
        public aixm.v5_1_1.CodeYesNoType Lighting { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("obstacleFree", IsNullable=true)]
        public aixm.v5_1_1.CodeYesNoType ObstacleFree { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("surfaceProperties", IsNullable=true)]
        public SurfaceCharacteristicsPropertyType SurfaceProperties { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("extent", IsNullable=true)]
        public ElevatedSurfacePropertyType Extent { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<NotePropertyType> _annotation;
        
        [System.Xml.Serialization.XmlElementAttribute("annotation", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<NotePropertyType> Annotation
        {
            get
            {
                return this._annotation;
            }
            private set
            {
                this._annotation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Annotation-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Annotation collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnnotationSpecified
        {
            get
            {
                return (this.Annotation.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="RunwayProtectAreaTimeSliceType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="RunwayProtectAreaTimeSliceType" /> class.</para>
        /// </summary>
        public RunwayProtectAreaTimeSliceType()
        {
            this._annotation = new System.Collections.ObjectModel.Collection<NotePropertyType>();
            this._extension = new System.Collections.ObjectModel.Collection<RunwayProtectAreaTimeSliceTypeExtension>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("type", IsNullable=true)]
        public aixm.v5_1_1.CodeRunwayProtectionAreaType Type { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("status", IsNullable=true)]
        public aixm.v5_1_1.CodeStatusOperationsType Status { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("protectedRunwayDirection", IsNullable=true)]
        public RunwayDirectionPropertyType ProtectedRunwayDirection { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RunwayProtectAreaTimeSliceTypeExtension> _extension;
        
        [System.Xml.Serialization.XmlElementAttribute("extension")]
        public System.Collections.ObjectModel.Collection<RunwayProtectAreaTimeSliceTypeExtension> Extension
        {
            get
            {
                return this._extension;
            }
            private set
            {
                this._extension = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Extension-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Extension collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtensionSpecified
        {
            get
            {
                return (this.Extension.Count != 0);
            }
        }
    }
}
