//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace aixm.v5_1_1
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TerminalArrivalAreaTimeSliceType", Namespace="http://www.aixm.aero/schema/5.1.1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("TerminalArrivalAreaTimeSlice", Namespace="http://www.aixm.aero/schema/5.1.1")]
    public partial class TerminalArrivalAreaTimeSliceType : aixm.v5_1_1.AbstractAIXMTimeSliceType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("arrivalAreaType", IsNullable=true)]
        public aixm.v5_1_1.CodeTAAType ArrivalAreaType { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("outerBufferWidth", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceType OuterBufferWidth { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("lateralBufferWidth", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceType LateralBufferWidth { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IF_fixDesignatedPoint", IsNullable=true)]
        public DesignatedPointPropertyType IF_FixDesignatedPoint { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IF_navaidSystem", IsNullable=true)]
        public NavaidPropertyType IF_NavaidSystem { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IF_position", IsNullable=true)]
        public PointPropertyType IF_Position { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IF_runwayPoint", IsNullable=true)]
        public RunwayCentrelinePointPropertyType IF_RunwayPoint { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IF_aimingPoint", IsNullable=true)]
        public TouchDownLiftOffPropertyType IF_AimingPoint { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IF_airportReferencePoint", IsNullable=true)]
        public AirportHeliportPropertyType IF_AirportReferencePoint { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IAF_fixDesignatedPoint", IsNullable=true)]
        public DesignatedPointPropertyType IAF_FixDesignatedPoint { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IAF_navaidSystem", IsNullable=true)]
        public NavaidPropertyType IAF_NavaidSystem { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IAF_position", IsNullable=true)]
        public PointPropertyType IAF_Position { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IAF_runwayPoint", IsNullable=true)]
        public RunwayCentrelinePointPropertyType IAF_RunwayPoint { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IAF_aimingPoint", IsNullable=true)]
        public TouchDownLiftOffPropertyType IAF_AimingPoint { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IAF_airportReferencePoint", IsNullable=true)]
        public AirportHeliportPropertyType IAF_AirportReferencePoint { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("buffer", IsNullable=true)]
        public SurfacePropertyType Buffer { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TerminalArrivalAreaSectorPropertyType> _sector;
        
        [System.Xml.Serialization.XmlElementAttribute("sector", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<TerminalArrivalAreaSectorPropertyType> Sector
        {
            get
            {
                return this._sector;
            }
            private set
            {
                this._sector = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Sector-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Sector collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SectorSpecified
        {
            get
            {
                return (this.Sector.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="TerminalArrivalAreaTimeSliceType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TerminalArrivalAreaTimeSliceType" /> class.</para>
        /// </summary>
        public TerminalArrivalAreaTimeSliceType()
        {
            this._sector = new System.Collections.ObjectModel.Collection<TerminalArrivalAreaSectorPropertyType>();
            this._annotation = new System.Collections.ObjectModel.Collection<NotePropertyType>();
            this._extension = new System.Collections.ObjectModel.Collection<TerminalArrivalAreaTimeSliceTypeExtension>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("approachRNAV", IsNullable=true)]
        public InstrumentApproachProcedurePropertyType ApproachRNAV { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<NotePropertyType> _annotation;
        
        [System.Xml.Serialization.XmlElementAttribute("annotation", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<NotePropertyType> Annotation
        {
            get
            {
                return this._annotation;
            }
            private set
            {
                this._annotation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Annotation-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Annotation collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnnotationSpecified
        {
            get
            {
                return (this.Annotation.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TerminalArrivalAreaTimeSliceTypeExtension> _extension;
        
        [System.Xml.Serialization.XmlElementAttribute("extension")]
        public System.Collections.ObjectModel.Collection<TerminalArrivalAreaTimeSliceTypeExtension> Extension
        {
            get
            {
                return this._extension;
            }
            private set
            {
                this._extension = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Extension-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Extension collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtensionSpecified
        {
            get
            {
                return (this.Extension.Count != 0);
            }
        }
    }
}
