//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace aixm.v5_1_1
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("UnitTimeSliceType", Namespace="http://www.aixm.aero/schema/5.1.1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("UnitTimeSlice", Namespace="http://www.aixm.aero/schema/5.1.1")]
    public partial class UnitTimeSliceType : aixm.v5_1_1.AbstractAIXMTimeSliceType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("name", IsNullable=true)]
        public aixm.v5_1_1.TextNameType Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("type", IsNullable=true)]
        public aixm.v5_1_1.CodeUnitType Type { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("compliantICAO", IsNullable=true)]
        public aixm.v5_1_1.CodeYesNoType CompliantICAO { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("designator", IsNullable=true)]
        public aixm.v5_1_1.CodeOrganisationDesignatorType Designator { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("military", IsNullable=true)]
        public aixm.v5_1_1.CodeMilitaryOperationsType Military { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("position", IsNullable=true)]
        public ElevatedPointPropertyType Position { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("airportLocation", IsNullable=true)]
        public AirportHeliportPropertyType AirportLocation { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ownerOrganisation", IsNullable=true)]
        public OrganisationAuthorityPropertyType OwnerOrganisation { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ContactInformationPropertyType> _contact;
        
        [System.Xml.Serialization.XmlElementAttribute("contact", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<ContactInformationPropertyType> Contact
        {
            get
            {
                return this._contact;
            }
            private set
            {
                this._contact = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Contact-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Contact collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ContactSpecified
        {
            get
            {
                return (this.Contact.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="UnitTimeSliceType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="UnitTimeSliceType" /> class.</para>
        /// </summary>
        public UnitTimeSliceType()
        {
            this._contact = new System.Collections.ObjectModel.Collection<ContactInformationPropertyType>();
            this._relatedUnit = new System.Collections.ObjectModel.Collection<UnitDependencyPropertyType>();
            this._availability = new System.Collections.ObjectModel.Collection<UnitAvailabilityPropertyType>();
            this._annotation = new System.Collections.ObjectModel.Collection<NotePropertyType>();
            this._extension = new System.Collections.ObjectModel.Collection<UnitTimeSliceTypeExtension>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<UnitDependencyPropertyType> _relatedUnit;
        
        [System.Xml.Serialization.XmlElementAttribute("relatedUnit", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<UnitDependencyPropertyType> RelatedUnit
        {
            get
            {
                return this._relatedUnit;
            }
            private set
            {
                this._relatedUnit = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die RelatedUnit-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the RelatedUnit collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RelatedUnitSpecified
        {
            get
            {
                return (this.RelatedUnit.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<UnitAvailabilityPropertyType> _availability;
        
        [System.Xml.Serialization.XmlElementAttribute("availability", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<UnitAvailabilityPropertyType> Availability
        {
            get
            {
                return this._availability;
            }
            private set
            {
                this._availability = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Availability-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Availability collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AvailabilitySpecified
        {
            get
            {
                return (this.Availability.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<NotePropertyType> _annotation;
        
        [System.Xml.Serialization.XmlElementAttribute("annotation", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<NotePropertyType> Annotation
        {
            get
            {
                return this._annotation;
            }
            private set
            {
                this._annotation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Annotation-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Annotation collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnnotationSpecified
        {
            get
            {
                return (this.Annotation.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<UnitTimeSliceTypeExtension> _extension;
        
        [System.Xml.Serialization.XmlElementAttribute("extension")]
        public System.Collections.ObjectModel.Collection<UnitTimeSliceTypeExtension> Extension
        {
            get
            {
                return this._extension;
            }
            private set
            {
                this._extension = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Extension-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Extension collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtensionSpecified
        {
            get
            {
                return (this.Extension.Count != 0);
            }
        }
    }
}
