//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace org.isotc211._2005.gmd
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>Information required enabling contact with the  responsible person and/or organisation</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CI_Contact_Type", Namespace="http://www.isotc211.org/2005/gmd")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CI_Contact", Namespace="http://www.isotc211.org/2005/gmd")]
    public partial class CI_Contact_Type : org.isotc211._2005.gco.AbstractObject_Type
    {
        
        [System.Xml.Serialization.XmlElementAttribute("phone")]
        public CI_Telephone_PropertyType Phone { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("address")]
        public CI_Address_PropertyType Address { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("onlineResource")]
        public CI_OnlineResource_PropertyType OnlineResource { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("hoursOfService")]
        public org.isotc211._2005.gco.CharacterString_PropertyType HoursOfService { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("contactInstructions")]
        public org.isotc211._2005.gco.CharacterString_PropertyType ContactInstructions { get; set; }
    }
}
