//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace org.isotc211._2005.gmd
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DQ_Scope_Type", Namespace="http://www.isotc211.org/2005/gmd")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("DQ_Scope", Namespace="http://www.isotc211.org/2005/gmd")]
    public partial class DQ_Scope_Type : org.isotc211._2005.gco.AbstractObject_Type
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("level")]
        public org.isotc211._2005.gmd.MD_ScopeCode_PropertyType Level { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("extent")]
        public org.isotc211._2005.gmd.EX_Extent_PropertyType Extent { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<org.isotc211._2005.gmd.MD_ScopeDescription_PropertyType> _levelDescription;
        
        [System.Xml.Serialization.XmlElementAttribute("levelDescription")]
        public System.Collections.ObjectModel.Collection<org.isotc211._2005.gmd.MD_ScopeDescription_PropertyType> LevelDescription
        {
            get
            {
                return this._levelDescription;
            }
            private set
            {
                this._levelDescription = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die LevelDescription-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the LevelDescription collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LevelDescriptionSpecified
        {
            get
            {
                return (this.LevelDescription.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="DQ_Scope_Type" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="DQ_Scope_Type" /> class.</para>
        /// </summary>
        public DQ_Scope_Type()
        {
            this._levelDescription = new System.Collections.ObjectModel.Collection<org.isotc211._2005.gmd.MD_ScopeDescription_PropertyType>();
        }
    }
}
