//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace org.isotc211._2005.gmd
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>Information about the domain of the raster cell</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MD_CoverageDescription_Type", Namespace="http://www.isotc211.org/2005/gmd")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("MD_CoverageDescription", Namespace="http://www.isotc211.org/2005/gmd")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_ImageDescription_Type))]
    public partial class MD_CoverageDescription_Type : AbstractMD_ContentInformation_Type
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("attributeDescription")]
        public org.isotc211._2005.gco.RecordType_PropertyType AttributeDescription { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("contentType")]
        public MD_CoverageContentTypeCode_PropertyType ContentType { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<MD_RangeDimension_PropertyType> _dimension;
        
        [System.Xml.Serialization.XmlElementAttribute("dimension")]
        public System.Collections.ObjectModel.Collection<MD_RangeDimension_PropertyType> Dimension
        {
            get
            {
                return this._dimension;
            }
            private set
            {
                this._dimension = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Dimension-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Dimension collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DimensionSpecified
        {
            get
            {
                return (this.Dimension.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="MD_CoverageDescription_Type" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MD_CoverageDescription_Type" /> class.</para>
        /// </summary>
        public MD_CoverageDescription_Type()
        {
            this._dimension = new System.Collections.ObjectModel.Collection<MD_RangeDimension_PropertyType>();
        }
    }
}
