//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace org.isotc211._2005.gmd
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MD_DataIdentification_Type", Namespace="http://www.isotc211.org/2005/gmd")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("MD_DataIdentification", Namespace="http://www.isotc211.org/2005/gmd")]
    public partial class MD_DataIdentification_Type : AbstractMD_Identification_Type
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<MD_SpatialRepresentationTypeCode_PropertyType> _spatialRepresentationType;
        
        [System.Xml.Serialization.XmlElementAttribute("spatialRepresentationType")]
        public System.Collections.ObjectModel.Collection<MD_SpatialRepresentationTypeCode_PropertyType> SpatialRepresentationType
        {
            get
            {
                return this._spatialRepresentationType;
            }
            private set
            {
                this._spatialRepresentationType = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die SpatialRepresentationType-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the SpatialRepresentationType collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SpatialRepresentationTypeSpecified
        {
            get
            {
                return (this.SpatialRepresentationType.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="MD_DataIdentification_Type" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MD_DataIdentification_Type" /> class.</para>
        /// </summary>
        public MD_DataIdentification_Type()
        {
            this._spatialRepresentationType = new System.Collections.ObjectModel.Collection<MD_SpatialRepresentationTypeCode_PropertyType>();
            this._spatialResolution = new System.Collections.ObjectModel.Collection<MD_Resolution_PropertyType>();
            this._language = new System.Collections.ObjectModel.Collection<org.isotc211._2005.gco.CharacterString_PropertyType>();
            this._characterSet = new System.Collections.ObjectModel.Collection<MD_CharacterSetCode_PropertyType>();
            this._topicCategory = new System.Collections.ObjectModel.Collection<MD_TopicCategoryCode_PropertyType>();
            this._extent = new System.Collections.ObjectModel.Collection<org.isotc211._2005.gmd.EX_Extent_PropertyType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<MD_Resolution_PropertyType> _spatialResolution;
        
        [System.Xml.Serialization.XmlElementAttribute("spatialResolution")]
        public System.Collections.ObjectModel.Collection<MD_Resolution_PropertyType> SpatialResolution
        {
            get
            {
                return this._spatialResolution;
            }
            private set
            {
                this._spatialResolution = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die SpatialResolution-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the SpatialResolution collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SpatialResolutionSpecified
        {
            get
            {
                return (this.SpatialResolution.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<org.isotc211._2005.gco.CharacterString_PropertyType> _language;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("language")]
        public System.Collections.ObjectModel.Collection<org.isotc211._2005.gco.CharacterString_PropertyType> Language
        {
            get
            {
                return this._language;
            }
            private set
            {
                this._language = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<MD_CharacterSetCode_PropertyType> _characterSet;
        
        [System.Xml.Serialization.XmlElementAttribute("characterSet")]
        public System.Collections.ObjectModel.Collection<MD_CharacterSetCode_PropertyType> CharacterSet
        {
            get
            {
                return this._characterSet;
            }
            private set
            {
                this._characterSet = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die CharacterSet-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the CharacterSet collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CharacterSetSpecified
        {
            get
            {
                return (this.CharacterSet.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<MD_TopicCategoryCode_PropertyType> _topicCategory;
        
        [System.Xml.Serialization.XmlElementAttribute("topicCategory")]
        public System.Collections.ObjectModel.Collection<MD_TopicCategoryCode_PropertyType> TopicCategory
        {
            get
            {
                return this._topicCategory;
            }
            private set
            {
                this._topicCategory = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die TopicCategory-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the TopicCategory collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TopicCategorySpecified
        {
            get
            {
                return (this.TopicCategory.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("environmentDescription")]
        public org.isotc211._2005.gco.CharacterString_PropertyType EnvironmentDescription { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<org.isotc211._2005.gmd.EX_Extent_PropertyType> _extent;
        
        [System.Xml.Serialization.XmlElementAttribute("extent")]
        public System.Collections.ObjectModel.Collection<org.isotc211._2005.gmd.EX_Extent_PropertyType> Extent
        {
            get
            {
                return this._extent;
            }
            private set
            {
                this._extent = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Extent-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Extent collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtentSpecified
        {
            get
            {
                return (this.Extent.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("supplementalInformation")]
        public org.isotc211._2005.gco.CharacterString_PropertyType SupplementalInformation { get; set; }
    }
}
