//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace org.isotc211._2005.gmd
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>New metadata element, not found in ISO 19115, which is required to describe geographic data</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MD_ExtendedElementInformation_Type", Namespace="http://www.isotc211.org/2005/gmd")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("MD_ExtendedElementInformation", Namespace="http://www.isotc211.org/2005/gmd")]
    public partial class MD_ExtendedElementInformation_Type : org.isotc211._2005.gco.AbstractObject_Type
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("name")]
        public org.isotc211._2005.gco.CharacterString_PropertyType Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("shortName")]
        public org.isotc211._2005.gco.CharacterString_PropertyType ShortName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("domainCode")]
        public org.isotc211._2005.gco.Integer_PropertyType DomainCode { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("definition")]
        public org.isotc211._2005.gco.CharacterString_PropertyType Definition { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("obligation")]
        public MD_ObligationCode_PropertyType Obligation { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("condition")]
        public org.isotc211._2005.gco.CharacterString_PropertyType Condition { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("dataType")]
        public MD_DatatypeCode_PropertyType DataType { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("maximumOccurrence")]
        public org.isotc211._2005.gco.CharacterString_PropertyType MaximumOccurrence { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("domainValue")]
        public org.isotc211._2005.gco.CharacterString_PropertyType DomainValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<org.isotc211._2005.gco.CharacterString_PropertyType> _parentEntity;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("parentEntity")]
        public System.Collections.ObjectModel.Collection<org.isotc211._2005.gco.CharacterString_PropertyType> ParentEntity
        {
            get
            {
                return this._parentEntity;
            }
            private set
            {
                this._parentEntity = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="MD_ExtendedElementInformation_Type" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MD_ExtendedElementInformation_Type" /> class.</para>
        /// </summary>
        public MD_ExtendedElementInformation_Type()
        {
            this._parentEntity = new System.Collections.ObjectModel.Collection<org.isotc211._2005.gco.CharacterString_PropertyType>();
            this._rationale = new System.Collections.ObjectModel.Collection<org.isotc211._2005.gco.CharacterString_PropertyType>();
            this._source = new System.Collections.ObjectModel.Collection<org.isotc211._2005.gmd.CI_ResponsibleParty_PropertyType>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("rule")]
        public org.isotc211._2005.gco.CharacterString_PropertyType Rule { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<org.isotc211._2005.gco.CharacterString_PropertyType> _rationale;
        
        [System.Xml.Serialization.XmlElementAttribute("rationale")]
        public System.Collections.ObjectModel.Collection<org.isotc211._2005.gco.CharacterString_PropertyType> Rationale
        {
            get
            {
                return this._rationale;
            }
            private set
            {
                this._rationale = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Rationale-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Rationale collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RationaleSpecified
        {
            get
            {
                return (this.Rationale.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<org.isotc211._2005.gmd.CI_ResponsibleParty_PropertyType> _source;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("source")]
        public System.Collections.ObjectModel.Collection<org.isotc211._2005.gmd.CI_ResponsibleParty_PropertyType> Source
        {
            get
            {
                return this._source;
            }
            private set
            {
                this._source = value;
            }
        }
    }
}
