//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace org.isotc211._2005.gmd
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>Description of the form of the data to be distributed</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MD_Format_Type", Namespace="http://www.isotc211.org/2005/gmd")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("MD_Format", Namespace="http://www.isotc211.org/2005/gmd")]
    public partial class MD_Format_Type : org.isotc211._2005.gco.AbstractObject_Type
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("name")]
        public org.isotc211._2005.gco.CharacterString_PropertyType Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("version")]
        public org.isotc211._2005.gco.CharacterString_PropertyType Version { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("amendmentNumber")]
        public org.isotc211._2005.gco.CharacterString_PropertyType AmendmentNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("specification")]
        public org.isotc211._2005.gco.CharacterString_PropertyType Specification { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("fileDecompressionTechnique")]
        public org.isotc211._2005.gco.CharacterString_PropertyType FileDecompressionTechnique { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<MD_Distributor_PropertyType> _formatDistributor;
        
        [System.Xml.Serialization.XmlElementAttribute("formatDistributor")]
        public System.Collections.ObjectModel.Collection<MD_Distributor_PropertyType> FormatDistributor
        {
            get
            {
                return this._formatDistributor;
            }
            private set
            {
                this._formatDistributor = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die FormatDistributor-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the FormatDistributor collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FormatDistributorSpecified
        {
            get
            {
                return (this.FormatDistributor.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="MD_Format_Type" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MD_Format_Type" /> class.</para>
        /// </summary>
        public MD_Format_Type()
        {
            this._formatDistributor = new System.Collections.ObjectModel.Collection<MD_Distributor_PropertyType>();
        }
    }
}
