//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace aero.aixm.schema._5_1_1.extensions.eur.adr
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AirspaceExtensionType", Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("AirspaceExtension", Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
    public partial class AirspaceExtensionType : aixm.v5_1_1.AbstractExtensionType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("flexibleUse", IsNullable=true)]
        public aixm.v5_1_1.CodeYesNoType FlexibleUse { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("level1", IsNullable=true)]
        public aixm.v5_1_1.CodeYesNoType Level1 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("level2", IsNullable=true)]
        public aixm.v5_1_1.CodeYesNoType Level2 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("level3", IsNullable=true)]
        public aixm.v5_1_1.CodeYesNoType Level3 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("usage", IsNullable=true)]
        public aero.aixm.schema._5_1_1.extensions.eur.adr.CodeFeatureUsageType Usage { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("responsibleAMC", IsNullable=true)]
        public aixm.v5_1_1.UnitPropertyType ResponsibleAMC { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<aixm.v5_1_1.RoutePortionPropertyType> _nearby;
        
        [System.Xml.Serialization.XmlElementAttribute("nearby", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<aixm.v5_1_1.RoutePortionPropertyType> Nearby
        {
            get
            {
                return this._nearby;
            }
            private set
            {
                this._nearby = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Nearby-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Nearby collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NearbySpecified
        {
            get
            {
                return (this.Nearby.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="AirspaceExtensionType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="AirspaceExtensionType" /> class.</para>
        /// </summary>
        public AirspaceExtensionType()
        {
            this._nearby = new System.Collections.ObjectModel.Collection<aixm.v5_1_1.RoutePortionPropertyType>();
            this._offload = new System.Collections.ObjectModel.Collection<aixm.v5_1_1.RoutePortionPropertyType>();
            this._notAffected = new System.Collections.ObjectModel.Collection<aixm.v5_1_1.RoutePortionPropertyType>();
            this._rsaActivation = new System.Collections.ObjectModel.Collection<aixm.v5_1_1.AirspaceActivationPropertyType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<aixm.v5_1_1.RoutePortionPropertyType> _offload;
        
        [System.Xml.Serialization.XmlElementAttribute("offload", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<aixm.v5_1_1.RoutePortionPropertyType> Offload
        {
            get
            {
                return this._offload;
            }
            private set
            {
                this._offload = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Offload-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Offload collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffloadSpecified
        {
            get
            {
                return (this.Offload.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<aixm.v5_1_1.RoutePortionPropertyType> _notAffected;
        
        [System.Xml.Serialization.XmlElementAttribute("notAffected", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<aixm.v5_1_1.RoutePortionPropertyType> NotAffected
        {
            get
            {
                return this._notAffected;
            }
            private set
            {
                this._notAffected = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die NotAffected-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the NotAffected collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NotAffectedSpecified
        {
            get
            {
                return (this.NotAffected.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<aixm.v5_1_1.AirspaceActivationPropertyType> _rsaActivation;
        
        [System.Xml.Serialization.XmlElementAttribute("rsaActivation", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<aixm.v5_1_1.AirspaceActivationPropertyType> RsaActivation
        {
            get
            {
                return this._rsaActivation;
            }
            private set
            {
                this._rsaActivation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die RsaActivation-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the RsaActivation collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RsaActivationSpecified
        {
            get
            {
                return (this.RsaActivation.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("isFBZ", IsNullable=true)]
        public aixm.v5_1_1.CodeYesNoType IsFBZ { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("defaultForActivation", IsNullable=true)]
        public aixm.v5_1_1.CodeYesNoType DefaultForActivation { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ownerRSA", IsNullable=true)]
        public aixm.v5_1_1.AirspacePropertyType OwnerRSA { get; set; }
    }
}
