//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace aero.aixm.schema._5_1_1.extensions.eur.adr
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ApproachLegTimeSliceType", Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ApproachLegTimeSlice", Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
    public partial class ApproachLegTimeSliceType : aixm.v5_1_1.AbstractAIXMTimeSliceType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("endConditionDesignator", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.CodeSegmentTerminationType EndConditionDesignator { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("legPath", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.CodeTrajectoryType LegPath { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("legTypeARINC", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.CodeSegmentPathType LegTypeARINC { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("course", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.ValBearingType Course { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("courseType", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.CodeCourseType CourseType { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("courseDirection", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.CodeDirectionReferenceType CourseDirection { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("turnDirection", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.CodeDirectionTurnType TurnDirection { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("speedLimit", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.ValSpeedType SpeedLimit { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("speedReference", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.CodeSpeedReferenceType SpeedReference { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("speedInterpretation", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.CodeAltitudeUseType SpeedInterpretation { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("bankAngle", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.ValAngleType BankAngle { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("length", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceType Length { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("duration", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.ValDurationType Duration { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("procedureTurnRequired", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.CodeYesNoType ProcedureTurnRequired { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("upperLimitAltitude", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceVerticalType UpperLimitAltitude { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("upperLimitReference", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.CodeVerticalReferenceType UpperLimitReference { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("lowerLimitAltitude", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceVerticalType LowerLimitAltitude { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("lowerLimitReference", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.CodeVerticalReferenceType LowerLimitReference { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("altitudeInterpretation", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.CodeAltitudeUseType AltitudeInterpretation { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("altitudeOverrideATC", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.ValDistanceVerticalType AltitudeOverrideATC { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("altitudeOverrideReference", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.CodeVerticalReferenceType AltitudeOverrideReference { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("verticalAngle", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.ValAngleType VerticalAngle { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("startPoint", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.TerminalSegmentPointPropertyType StartPoint { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("endPoint", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.TerminalSegmentPointPropertyType EndPoint { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("trajectory", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.CurvePropertyType Trajectory { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("arcCentre", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.TerminalSegmentPointPropertyType ArcCentre { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("angle", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.AngleIndicationPropertyType Angle { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("distance", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.DistanceIndicationPropertyType Distance { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<aixm.v5_1_1.AircraftCharacteristicPropertyType> _aircraftCategory;
        
        [System.Xml.Serialization.XmlElementAttribute("aircraftCategory", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<aixm.v5_1_1.AircraftCharacteristicPropertyType> AircraftCategory
        {
            get
            {
                return this._aircraftCategory;
            }
            private set
            {
                this._aircraftCategory = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die AircraftCategory-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the AircraftCategory collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AircraftCategorySpecified
        {
            get
            {
                return (this.AircraftCategory.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="ApproachLegTimeSliceType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ApproachLegTimeSliceType" /> class.</para>
        /// </summary>
        public ApproachLegTimeSliceType()
        {
            this._aircraftCategory = new System.Collections.ObjectModel.Collection<aixm.v5_1_1.AircraftCharacteristicPropertyType>();
            this._designSurface = new System.Collections.ObjectModel.Collection<aixm.v5_1_1.ObstacleAssessmentAreaPropertyType>();
            this._annotation = new System.Collections.ObjectModel.Collection<aixm.v5_1_1.NotePropertyType>();
            this._extension = new System.Collections.ObjectModel.Collection<ApproachLegTimeSliceTypeExtension>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("holding", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.HoldingUsePropertyType Holding { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<aixm.v5_1_1.ObstacleAssessmentAreaPropertyType> _designSurface;
        
        [System.Xml.Serialization.XmlElementAttribute("designSurface", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<aixm.v5_1_1.ObstacleAssessmentAreaPropertyType> DesignSurface
        {
            get
            {
                return this._designSurface;
            }
            private set
            {
                this._designSurface = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die DesignSurface-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the DesignSurface collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DesignSurfaceSpecified
        {
            get
            {
                return (this.DesignSurface.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<aixm.v5_1_1.NotePropertyType> _annotation;
        
        [System.Xml.Serialization.XmlElementAttribute("annotation", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<aixm.v5_1_1.NotePropertyType> Annotation
        {
            get
            {
                return this._annotation;
            }
            private set
            {
                this._annotation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Annotation-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Annotation collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnnotationSpecified
        {
            get
            {
                return (this.Annotation.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("approach", Namespace="http://www.aixm.aero/schema/5.1.1", IsNullable=true)]
        public aixm.v5_1_1.InstrumentApproachProcedurePropertyType Approach { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ApproachLegTimeSliceTypeExtension> _extension;
        
        [System.Xml.Serialization.XmlElementAttribute("extension")]
        public System.Collections.ObjectModel.Collection<ApproachLegTimeSliceTypeExtension> Extension
        {
            get
            {
                return this._extension;
            }
            private set
            {
                this._extension = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Extension-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Extension collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtensionSpecified
        {
            get
            {
                return (this.Extension.Count != 0);
            }
        }
    }
}
