//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.

using aixm.v5_1_1;

namespace aero.aixm.schema._5_1_1.extensions.eur.adr
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FlightRestrictionExtensionType", Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("FlightRestrictionExtension", Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
    public partial class FlightRestrictionExtensionType : AbstractExtensionType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("processingIndicator", IsNullable=true)]
        public aero.aixm.schema._5_1_1.extensions.eur.adr.CodeProcessingIndicatorType ProcessingIndicator { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("enabled", IsNullable=true)]
        public CodeYesNoType Enabled { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("usage", IsNullable=true)]
        public aero.aixm.schema._5_1_1.extensions.eur.adr.CodeFeatureUsageType Usage { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("isFUA", IsNullable=true)]
        public CodeYesNoType IsFUA { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("fuaDefaultActive", IsNullable=true)]
        public CodeYesNoType FuaDefaultActive { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("verticalLimitReference", IsNullable=true)]
        public aero.aixm.schema._5_1_1.extensions.eur.adr.CodeVerticalLimitReferenceType VerticalLimitReference { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("dependentVerticalLimits", IsNullable=true)]
        public CodeYesNoType DependentVerticalLimits { get; set; }
    }
}
