//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.

using aixm.v5_1_1;

namespace aero.aixm.schema._5_1_1.extensions.eur.adr
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IntermediateSignificantPointType", Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("IntermediateSignificantPoint", Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
    public partial class IntermediateSignificantPointType : AbstractAIXMObjectType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("pointChoice_fixDesignatedPoint", IsNullable=true)]
        public DesignatedPointPropertyType PointChoice_FixDesignatedPoint { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("pointChoice_navaidSystem", IsNullable=true)]
        public NavaidPropertyType PointChoice_NavaidSystem { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("pointChoice_position", IsNullable=true)]
        public PointPropertyType PointChoice_Position { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("pointChoice_runwayPoint", IsNullable=true)]
        public RunwayCentrelinePointPropertyType PointChoice_RunwayPoint { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("pointChoice_aimingPoint", IsNullable=true)]
        public TouchDownLiftOffPropertyType PointChoice_AimingPoint { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("pointChoice_airportReferencePoint", IsNullable=true)]
        public AirportHeliportPropertyType PointChoice_AirportReferencePoint { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<NotePropertyType> _annotation;
        
        [System.Xml.Serialization.XmlElementAttribute("annotation", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<NotePropertyType> Annotation
        {
            get
            {
                return this._annotation;
            }
            private set
            {
                this._annotation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Annotation-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Annotation collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnnotationSpecified
        {
            get
            {
                return (this.Annotation.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="IntermediateSignificantPointType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="IntermediateSignificantPointType" /> class.</para>
        /// </summary>
        public IntermediateSignificantPointType()
        {
            this._annotation = new System.Collections.ObjectModel.Collection<NotePropertyType>();
            this._extension = new System.Collections.ObjectModel.Collection<IntermediateSignificantPointTypeExtension>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<IntermediateSignificantPointTypeExtension> _extension;
        
        [System.Xml.Serialization.XmlElementAttribute("extension")]
        public System.Collections.ObjectModel.Collection<IntermediateSignificantPointTypeExtension> Extension
        {
            get
            {
                return this._extension;
            }
            private set
            {
                this._extension = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Extension-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Extension collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtensionSpecified
        {
            get
            {
                return (this.Extension.Count != 0);
            }
        }
    }
}
