//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace aero.aixm.schema._5_1_1.extensions.eur.adr
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RouteSegmentVerticalLimitTypeExtension", Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR", AnonymousType=true)]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RouteSegmentVerticalLimitTypeExtension
    {
        
        [System.Xml.Serialization.XmlElementAttribute("AircraftCharacteristicExtension", Type=typeof(AircraftCharacteristicExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("AirportHeliportExtension", Type=typeof(AirportHeliportExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("AirspaceExtension", Type=typeof(AirspaceExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("AirspaceActivationExtension", Type=typeof(AirspaceActivationExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("DesignatedPointExtension", Type=typeof(DesignatedPointExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("FlightCharacteristicExtension", Type=typeof(FlightCharacteristicExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("FlightConditionElementExtension", Type=typeof(FlightConditionElementExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("FlightRestrictionExtension", Type=typeof(FlightRestrictionExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("NavaidExtension", Type=typeof(NavaidExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("ProcedureExtension", Type=typeof(ProcedureExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("RouteExtension", Type=typeof(RouteExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("RouteAvailabilityExtension", Type=typeof(RouteAvailabilityExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("RoutePortionExtension", Type=typeof(RoutePortionExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("RouteSegmentExtension", Type=typeof(RouteSegmentExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("StandardInstrumentArrivalExtension", Type=typeof(StandardInstrumentArrivalExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("StandardInstrumentDepartureExtension", Type=typeof(StandardInstrumentDepartureExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("TimesheetExtension", Type=typeof(TimesheetExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("AbstractPropertiesWithScheduleExtension", Namespace="http://www.aixm.aero/schema/5.1.1")]
        public aixm.v5_1_1.AbstractExtensionType AbstractPropertiesWithScheduleExtension { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("AircraftCharacteristicExtension", Type=typeof(AircraftCharacteristicExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("AirportHeliportExtension", Type=typeof(AirportHeliportExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("AirspaceExtension", Type=typeof(AirspaceExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("AirspaceActivationExtension", Type=typeof(AirspaceActivationExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("DesignatedPointExtension", Type=typeof(DesignatedPointExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("FlightCharacteristicExtension", Type=typeof(FlightCharacteristicExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("FlightConditionElementExtension", Type=typeof(FlightConditionElementExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("FlightRestrictionExtension", Type=typeof(FlightRestrictionExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("NavaidExtension", Type=typeof(NavaidExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("ProcedureExtension", Type=typeof(ProcedureExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("RouteExtension", Type=typeof(RouteExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("RouteAvailabilityExtension", Type=typeof(RouteAvailabilityExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("RoutePortionExtension", Type=typeof(RoutePortionExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("RouteSegmentExtension", Type=typeof(RouteSegmentExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("StandardInstrumentArrivalExtension", Type=typeof(StandardInstrumentArrivalExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("StandardInstrumentDepartureExtension", Type=typeof(StandardInstrumentDepartureExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("TimesheetExtension", Type=typeof(TimesheetExtensionType), Namespace="http://www.aixm.aero/schema/5.1.1/extensions/EUR/ADR")]
        [System.Xml.Serialization.XmlElementAttribute("AbstractRouteSegmentVerticalLimitExtension")]
        public aixm.v5_1_1.AbstractExtensionType AbstractRouteSegmentVerticalLimitExtension { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _owns = false;
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlAttributeAttribute("owns")]
        public bool Owns
        {
            get
            {
                return this._owns;
            }
            set
            {
                this._owns = value;
            }
        }
    }
}
