//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace org.w3._1999.xlink
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("showType", Namespace="http://www.w3.org/1999/xlink")]
    public enum ShowType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("new")]
        New,
        
        [System.Xml.Serialization.XmlEnumAttribute("replace")]
        Replace,
        
        [System.Xml.Serialization.XmlEnumAttribute("embed")]
        Embed,
        
        [System.Xml.Serialization.XmlEnumAttribute("other")]
        Other,
        
        [System.Xml.Serialization.XmlEnumAttribute("none")]
        None,
    }
}
