//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace net.opengis.gml._3
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>gml:CodeType is a generalized type to be used for a term, keyword or name.
    ///It adds a XML attribute codeSpace to a term, where the value of the codeSpace attribute (if present) shall indicate a dictionary, thesaurus, classification scheme, authority, or pattern for the term.</para>
    /// <para>The gml:name property provides a label or identifier for the object, commonly a descriptive name. An object may have several names, typically assigned by different authorities. gml:name uses the gml:CodeType content model.  The authority for a name is indicated by the value of its (optional) codeSpace attribute.  The name may or may not be unique, as determined by the rules of the organization responsible for the codeSpace.  In common usage there will be one name per authority, so a processing application may select the name from its preferred codeSpace.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CodeType", Namespace="http://www.opengis.net/gml/3.2")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("name", Namespace="http://www.opengis.net/gml/3.2")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(org.isotc211._2005.gco.AbstractGenericName))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(net.opengis.gml._3.AnchorDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(net.opengis.gml._3.AnchorPoint))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(net.opengis.gml._3.AxisAbbrev))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(net.opengis.gml._3.AxisDirection))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(net.opengis.gml._3.CatalogSymbol))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(net.opengis.gml._3.Category))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CodeWithAuthorityType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(net.opengis.gml._3.DerivedCRSType2))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(net.opengis.gml._3.Formula))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(org.isotc211._2005.gco.LocalName))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(net.opengis.gml._3.LocationKeyWord))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(net.opengis.gml._3.LocationName))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(net.opengis.gml._3.MethodFormula))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(net.opengis.gml._3.PixelInCell))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(net.opengis.gml._3.RangeMeaning))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(org.isotc211._2005.gco.ScopedName))]
    public partial class CodeType
    {
        
        /// <summary>
        /// <para xml:lang="de">Ruft den Text ab oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("codeSpace")]
        public string CodeSpace { get; set; }
    }
}
