//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace net.opengis.gml._3
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>gml:CoordinateSystemAxis is a definition of a coordinate system axis.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CoordinateSystemAxisType", Namespace="http://www.opengis.net/gml/3.2")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CoordinateSystemAxis", Namespace="http://www.opengis.net/gml/3.2")]
    public partial class CoordinateSystemAxisType : net.opengis.gml._3.IdentifiedObjectType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("axisAbbrev")]
        public net.opengis.gml._3.CodeType AxisAbbrev { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("axisDirection")]
        public net.opengis.gml._3.CodeWithAuthorityType AxisDirection { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("minimumValue")]
        public double MinimumValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die MinimumValue-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the MinimumValue property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinimumValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("maximumValue")]
        public double MaximumValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die MaximumValue-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the MaximumValue property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaximumValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("rangeMeaning")]
        public net.opengis.gml._3.CodeWithAuthorityType RangeMeaning { get; set; }
        
        /// <summary>
        /// <para>The uom attribute provides an identifier of the unit of measure used for this coordinate system axis. The value of this coordinate in a coordinate tuple shall be recorded using this unit of measure, whenever those coordinates use a coordinate reference system that uses a coordinate system that uses this axis.</para>
        /// <para>The simple type gml:UomIdentifer defines the syntax and value space of the unit of measure identifier.</para>
        /// <para xml:lang="en">Pattern: ([^: \n\r\t]+)|(([a-zA-Z][a-zA-Z0-9\-\+\.]*:|\.\./|\./|#).*).</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([^: \\n\\r\\t]+)|(([a-zA-Z][a-zA-Z0-9\\-\\+\\.]*:|\\.\\./|\\./|#).*)")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("uom")]
        public string Uom { get; set; }
    }
}
