//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace net.opengis.gml._3
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>Envelope defines an extent using a pair of positions defining opposite corners in arbitrary dimensions. The first direct position is the "lower corner" (a coordinate position consisting of all the minimal ordinates for each dimension for all points within the envelope), the second one the "upper corner" (a coordinate position consisting of all the maximal ordinates for each dimension for all points within the envelope).
    ///The use of the properties "coordinates" and "pos" has been deprecated. The explicitly named properties "lowerCorner" and "upperCorner" shall be used instead.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EnvelopeType", Namespace="http://www.opengis.net/gml/3.2")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Envelope", Namespace="http://www.opengis.net/gml/3.2")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(net.opengis.gml._3.EnvelopeWithTimePeriodType))]
    public partial class EnvelopeType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("lowerCorner")]
        public DirectPositionType LowerCorner { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("upperCorner")]
        public DirectPositionType UpperCorner { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<DirectPositionType> _pos;
        
        [System.Xml.Serialization.XmlElementAttribute("pos")]
        public System.Collections.ObjectModel.Collection<DirectPositionType> Pos
        {
            get
            {
                return this._pos;
            }
            private set
            {
                this._pos = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Pos-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Pos collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PosSpecified
        {
            get
            {
                return (this.Pos.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="EnvelopeType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="EnvelopeType" /> class.</para>
        /// </summary>
        public EnvelopeType()
        {
            this._pos = new System.Collections.ObjectModel.Collection<DirectPositionType>();
            this.AxisLabels = new System.Collections.ObjectModel.Collection<string>();
            this.UomLabels = new System.Collections.ObjectModel.Collection<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("coordinates")]
        public net.opengis.gml._3.CoordinatesType Coordinates { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("srsName")]
        public string SrsName { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("srsDimension")]
        public string SrsDimension { get; set; }
        
        /// <summary>
        /// <para>A type for a list of values of the respective simple type.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("axisLabels")]
        public System.Collections.ObjectModel.Collection<string> AxisLabels { get; private set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die AxisLabels-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the AxisLabels collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AxisLabelsSpecified
        {
            get
            {
                return (this.AxisLabels.Count != 0);
            }
        }
        
        /// <summary>
        /// <para>A type for a list of values of the respective simple type.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("uomLabels")]
        public System.Collections.ObjectModel.Collection<string> UomLabels { get; private set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die UomLabels-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the UomLabels collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UomLabelsSpecified
        {
            get
            {
                return (this.UomLabels.Count != 0);
            }
        }
    }
}
