//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace net.opengis.gml._3
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("GeocentricCRSType", Namespace="http://www.opengis.net/gml/3.2")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("GeocentricCRS", Namespace="http://www.opengis.net/gml/3.2")]
    public partial class GeocentricCRSType : net.opengis.gml._3.AbstractCRSType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("usesCartesianCS")]
        public net.opengis.gml._3.CartesianCSPropertyType UsesCartesianCS { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("usesSphericalCS")]
        public net.opengis.gml._3.SphericalCSPropertyType UsesSphericalCS { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("usesGeodeticDatum")]
        public net.opengis.gml._3.GeodeticDatumPropertyType UsesGeodeticDatum { get; set; }
    }
}
