//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace net.opengis.gml._3
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>If a feature has a property which takes an array of geometry elements as its value, this is called a geometry array property. A generic type for such a geometry property is GeometryArrayPropertyType. 
    ///The elements are always contained inline in the array property, referencing geometry elements or arrays of geometry elements via XLinks is not supported.</para>
    /// <para>This property element contains a list of geometry elements. The order of the elements is significant and shall be preserved when processing the array.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("GeometryArrayPropertyType", Namespace="http://www.opengis.net/gml/3.2")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("geometryMembers", Namespace="http://www.opengis.net/gml/3.2")]
    public partial class GeometryArrayPropertyType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AbstractGeometryType> _abstractGeometry;
        
        [System.Xml.Serialization.XmlElementAttribute("AbstractGeometricPrimitive", Type=typeof(AbstractGeometricPrimitiveType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("AbstractGeometricAggregate", Type=typeof(net.opengis.gml._3.AbstractGeometricAggregateType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("GeometricComplex", Type=typeof(net.opengis.gml._3.GeometricComplexType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("Grid", Type=typeof(net.opengis.gml._3.GridType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("Point", Type=typeof(PointType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("AbstractCurve", Type=typeof(AbstractCurveType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("AbstractSurface", Type=typeof(net.opengis.gml._3.AbstractSurfaceType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("AbstractSolid", Type=typeof(net.opengis.gml._3.AbstractSolidType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("Point", Type=typeof(aixm.v5_1_1.PointType), Namespace="http://www.aixm.aero/schema/5.1.1")]
        [System.Xml.Serialization.XmlElementAttribute("ElevatedPoint", Type=typeof(aixm.v5_1_1.ElevatedPointType), Namespace="http://www.aixm.aero/schema/5.1.1")]
        [System.Xml.Serialization.XmlElementAttribute("LineString", Type=typeof(LineStringType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("AbstractRing", Type=typeof(net.opengis.gml._3.AbstractRingType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("Curve", Type=typeof(net.opengis.gml._3.CurveType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("OrientableCurve", Type=typeof(net.opengis.gml._3.OrientableCurveType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("CompositeCurve", Type=typeof(net.opengis.gml._3.CompositeCurveType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("LinearRing", Type=typeof(net.opengis.gml._3.LinearRingType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("Ring", Type=typeof(net.opengis.gml._3.RingType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("Curve", Type=typeof(aixm.v5_1_1.CurveType), Namespace="http://www.aixm.aero/schema/5.1.1")]
        [System.Xml.Serialization.XmlElementAttribute("ElevatedCurve", Type=typeof(aixm.v5_1_1.ElevatedCurveType), Namespace="http://www.aixm.aero/schema/5.1.1")]
        [System.Xml.Serialization.XmlElementAttribute("Polygon", Type=typeof(net.opengis.gml._3.PolygonType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("Surface", Type=typeof(net.opengis.gml._3.SurfaceType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("OrientableSurface", Type=typeof(net.opengis.gml._3.OrientableSurfaceType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("Shell", Type=typeof(net.opengis.gml._3.ShellType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("CompositeSurface", Type=typeof(net.opengis.gml._3.CompositeSurfaceType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("Tin", Type=typeof(net.opengis.gml._3.TinType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("Surface", Type=typeof(aixm.v5_1_1.SurfaceType), Namespace="http://www.aixm.aero/schema/5.1.1")]
        [System.Xml.Serialization.XmlElementAttribute("ElevatedSurface", Type=typeof(aixm.v5_1_1.ElevatedSurfaceType), Namespace="http://www.aixm.aero/schema/5.1.1")]
        [System.Xml.Serialization.XmlElementAttribute("Solid", Type=typeof(net.opengis.gml._3.SolidType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("CompositeSolid", Type=typeof(net.opengis.gml._3.CompositeSolidType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("MultiGeometry", Type=typeof(net.opengis.gml._3.MultiGeometryType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("MultiPoint", Type=typeof(net.opengis.gml._3.MultiPointType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("MultiCurve", Type=typeof(net.opengis.gml._3.MultiCurveType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("MultiSurface", Type=typeof(net.opengis.gml._3.MultiSurfaceType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("MultiSolid", Type=typeof(net.opengis.gml._3.MultiSolidType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("RectifiedGrid", Type=typeof(net.opengis.gml._3.RectifiedGridType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("AbstractGeometry")]
        public System.Collections.ObjectModel.Collection<AbstractGeometryType> AbstractGeometry
        {
            get
            {
                return this._abstractGeometry;
            }
            private set
            {
                this._abstractGeometry = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die AbstractGeometry-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the AbstractGeometry collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AbstractGeometrySpecified
        {
            get
            {
                return (this.AbstractGeometry.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="GeometryArrayPropertyType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="GeometryArrayPropertyType" /> class.</para>
        /// </summary>
        public GeometryArrayPropertyType()
        {
            this._abstractGeometry = new System.Collections.ObjectModel.Collection<AbstractGeometryType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _owns = false;
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlAttributeAttribute("owns")]
        public bool Owns
        {
            get
            {
                return this._owns;
            }
            set
            {
                this._owns = value;
            }
        }
    }
}
