//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace net.opengis.gml._3
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>gml:ImageCRS is an engineering coordinate reference system applied to locations in images. Image coordinate reference systems are treated as a separate sub-type because the definition of the associated image datum contains two attributes not relevant to other engineering datums.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ImageCRSType", Namespace="http://www.opengis.net/gml/3.2")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ImageCRS", Namespace="http://www.opengis.net/gml/3.2")]
    public partial class ImageCRSType : net.opengis.gml._3.AbstractCRSType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("cartesianCS")]
        public net.opengis.gml._3.CartesianCSPropertyType CartesianCS { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("affineCS")]
        public net.opengis.gml._3.AffineCSPropertyType AffineCS { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("usesObliqueCartesianCS")]
        public ObliqueCartesianCSPropertyType UsesObliqueCartesianCS { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("imageDatum")]
        public net.opengis.gml._3.ImageDatumPropertyType ImageDatum { get; set; }
    }
}
