//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace net.opengis.gml._3
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>gml:LineStringSegmentArrayPropertyType provides a container for line strings.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LineStringSegmentArrayPropertyType", Namespace="http://www.opengis.net/gml/3.2")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LineStringSegmentArrayPropertyType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<LineStringSegmentType> _lineStringSegment;
        
        [System.Xml.Serialization.XmlElementAttribute("LineStringSegment")]
        public System.Collections.ObjectModel.Collection<LineStringSegmentType> LineStringSegment
        {
            get
            {
                return this._lineStringSegment;
            }
            private set
            {
                this._lineStringSegment = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die LineStringSegment-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the LineStringSegment collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LineStringSegmentSpecified
        {
            get
            {
                return (this.LineStringSegment.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="LineStringSegmentArrayPropertyType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="LineStringSegmentArrayPropertyType" /> class.</para>
        /// </summary>
        public LineStringSegmentArrayPropertyType()
        {
            this._lineStringSegment = new System.Collections.ObjectModel.Collection<LineStringSegmentType>();
        }
    }
}
