//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace net.opengis.gml._3
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>A gml:MultiPoint consists of one or more gml:Points.
    ///The members of the geometric aggregate may be specified either using the "standard" property (gml:pointMember) or the array property (gml:pointMembers). It is also valid to use both the "standard" and the array properties in the same collection.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MultiPointType", Namespace="http://www.opengis.net/gml/3.2")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("MultiPoint", Namespace="http://www.opengis.net/gml/3.2")]
    public partial class MultiPointType : AbstractGeometricAggregateType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<net.opengis.gml._3.PointPropertyType> _pointMember;
        
        [System.Xml.Serialization.XmlElementAttribute("pointMember")]
        public System.Collections.ObjectModel.Collection<net.opengis.gml._3.PointPropertyType> PointMember
        {
            get
            {
                return this._pointMember;
            }
            private set
            {
                this._pointMember = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die PointMember-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the PointMember collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PointMemberSpecified
        {
            get
            {
                return (this.PointMember.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="MultiPointType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MultiPointType" /> class.</para>
        /// </summary>
        public MultiPointType()
        {
            this._pointMember = new System.Collections.ObjectModel.Collection<net.opengis.gml._3.PointPropertyType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("pointMembers")]
        public net.opengis.gml._3.PointArrayPropertyType PointMembers { get; set; }
    }
}
