//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace net.opengis.gml._3
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>The content model is a straightforward extension of gml:AbstractFeatureType; it automatically has the gml:identifier, gml:description, gml:descriptionReference, gml:name, and gml:boundedBy properties. 
    ///The gml:validTime element describes the time of the observation. Note that this may be a time instant or a time period.
    ///The gml:using property contains or references a description of a sensor, instrument or procedure used for the observation.
    ///The gml:target property contains or references the specimen, region or station which is the object of the observation. This property is particularly useful for remote observations, such as photographs, where a generic location property might apply to the location of the camera or the location of the field of view, and thus may be ambiguous.  
    ///The gml:subject element is provided as a convenient synonym for gml:target. This is the term commonly used in phtotography.  
    ///The gml:resultOf property indicates the result of the observation.  The value may be inline, or a reference to a value elsewhere.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ObservationType", Namespace="http://www.opengis.net/gml/3.2")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Observation", Namespace="http://www.opengis.net/gml/3.2")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DirectedObservationAtDistanceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DirectedObservationType))]
    public partial class ObservationType : net.opengis.gml._3.AbstractFeatureType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("validTime")]
        public net.opengis.gml._3.TimePrimitivePropertyType ValidTime { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("using")]
        public ProcedurePropertyType Using { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("target")]
        public TargetPropertyType Target { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("resultOf")]
        public ResultType ResultOf { get; set; }
    }
}
