//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace net.opengis.gml._3
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>gml:OperationMethod is a method (algorithm or procedure) used to perform a coordinate operation. Most operation methods use a number of operation parameters, although some coordinate conversions use none. Each coordinate operation using the method assigns values to these parameters.
    ///The parameter elements are an unordered list of associations to the set of operation parameters and parameter groups used by this operation method.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("OperationMethodType", Namespace="http://www.opengis.net/gml/3.2")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("OperationMethod", Namespace="http://www.opengis.net/gml/3.2")]
    public partial class OperationMethodType : net.opengis.gml._3.IdentifiedObjectType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("formulaCitation")]
        public FormulaCitation FormulaCitation { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("formula")]
        public net.opengis.gml._3.CodeType Formula { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("sourceDimensions")]
        public string SourceDimensions { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("targetDimensions")]
        public string TargetDimensions { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AbstractGeneralOperationParameterPropertyType> _parameter;
        
        [System.Xml.Serialization.XmlElementAttribute("parameter")]
        public System.Collections.ObjectModel.Collection<AbstractGeneralOperationParameterPropertyType> Parameter
        {
            get
            {
                return this._parameter;
            }
            private set
            {
                this._parameter = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Parameter-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Parameter collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ParameterSpecified
        {
            get
            {
                return (this.Parameter.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="OperationMethodType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="OperationMethodType" /> class.</para>
        /// </summary>
        public OperationMethodType()
        {
            this._parameter = new System.Collections.ObjectModel.Collection<AbstractGeneralOperationParameterPropertyType>();
        }
    }
}
