//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace net.opengis.gml._3
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>OrientableSurface consists of a surface and an orientation. If the orientation is "+", then the OrientableSurface is identical to the baseSurface. If the orientation is "-", then the OrientableSurface is a reference to a gml:AbstractSurface with an up-normal that reverses the direction for this OrientableSurface, the sense of "the top of the surface".</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("OrientableSurfaceType", Namespace="http://www.opengis.net/gml/3.2")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("OrientableSurface", Namespace="http://www.opengis.net/gml/3.2")]
    public partial class OrientableSurfaceType : net.opengis.gml._3.AbstractSurfaceType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("baseSurface")]
        public net.opengis.gml._3.SurfacePropertyType BaseSurface { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private net.opengis.gml._3.SignType _orientation = net.opengis.gml._3.SignType.Plus;
        
        [System.ComponentModel.DefaultValueAttribute(net.opengis.gml._3.SignType.Plus)]
        [System.Xml.Serialization.XmlAttributeAttribute("orientation")]
        public net.opengis.gml._3.SignType Orientation
        {
            get
            {
                return this._orientation;
            }
            set
            {
                this._orientation = value;
            }
        }
    }
}
