//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace net.opengis.gml._3
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>A Point is defined by a single coordinate tuple. The direct position of a point is specified by the pos element which is of type DirectPositionType.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PointType", Namespace="http://www.opengis.net/gml/3.2")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Point", Namespace="http://www.opengis.net/gml/3.2")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(aixm.v5_1_1.ElevatedPointType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(aixm.v5_1_1.PointType))]
    public partial class PointType : AbstractGeometricPrimitiveType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("pos")]
        public DirectPositionType Pos { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("coordinates")]
        public net.opengis.gml._3.CoordinatesType Coordinates { get; set; }
    }
}
