//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace net.opengis.gml._3
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SecondDefiningParameter", Namespace="http://www.opengis.net/gml/3.2", AnonymousType=true)]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("SecondDefiningParameter", Namespace="http://www.opengis.net/gml/3.2")]
    public partial class SecondDefiningParameter2
    {
        
        [System.Xml.Serialization.XmlElementAttribute("inverseFlattening")]
        public net.opengis.gml._3.MeasureType InverseFlattening { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("semiMinorAxis")]
        public net.opengis.gml._3.LengthType SemiMinorAxis { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _isSphere = true;
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        [System.Xml.Serialization.XmlElementAttribute("isSphere")]
        public bool IsSphere
        {
            get
            {
                return this._isSphere;
            }
            set
            {
                this._isSphere = value;
            }
        }
    }
}
