//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace net.opengis.gml._3
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>gml:TimePeriod acts as a one-dimensional geometric primitive that represents an identifiable extent in time.
    ///The location in of a gml:TimePeriod is described by the temporal positions of the instants at which it begins and ends. The length of the period is equal to the temporal distance between the two bounding temporal positions. 
    ///Both beginning and end may be described in terms of their direct position using gml:TimePositionType which is an XML Schema simple content type, or by reference to an indentifiable time instant using gml:TimeInstantPropertyType.
    ///Alternatively a limit of a gml:TimePeriod may use the conventional GML property model to make a reference to a time instant described elsewhere, or a limit may be indicated as a direct position.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TimePeriodType", Namespace="http://www.opengis.net/gml/3.2")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("TimePeriod", Namespace="http://www.opengis.net/gml/3.2")]
    public partial class TimePeriodType : AbstractTimeGeometricPrimitiveType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("beginPosition")]
        public TimePositionType BeginPosition { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("begin")]
        public TimeInstantPropertyType Begin { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("endPosition")]
        public TimePositionType EndPosition { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("end")]
        public TimeInstantPropertyType End { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("duration")]
        public string Duration { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("timeInterval")]
        public TimeIntervalLengthType TimeInterval { get; set; }
    }
}
