//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace net.opengis.gml._3
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>gml:Transformation is a concrete object element derived from gml:GeneralTransformation (13.6.2.13).
    ///This concrete object can be used for all operation methods, without using a GML Application Schema that defines operation-method-specialized element names and contents, especially for methods with only one Transformation instance.
    ///The parameterValue elements are an unordered list of composition associations to the set of parameter values used by this conversion operation.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TransformationType", Namespace="http://www.opengis.net/gml/3.2")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Transformation", Namespace="http://www.opengis.net/gml/3.2")]
    public partial class TransformationType : AbstractGeneralTransformationType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("method")]
        public OperationMethodPropertyType Method { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AbstractGeneralParameterValuePropertyType> _parameterValue;
        
        [System.Xml.Serialization.XmlElementAttribute("parameterValue")]
        public System.Collections.ObjectModel.Collection<AbstractGeneralParameterValuePropertyType> ParameterValue
        {
            get
            {
                return this._parameterValue;
            }
            private set
            {
                this._parameterValue = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die ParameterValue-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the ParameterValue collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ParameterValueSpecified
        {
            get
            {
                return (this.ParameterValue.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="TransformationType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TransformationType" /> class.</para>
        /// </summary>
        public TransformationType()
        {
            this._parameterValue = new System.Collections.ObjectModel.Collection<AbstractGeneralParameterValuePropertyType>();
        }
    }
}
