//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace net.opengis.gml._3
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>The element gml:unitOfMeasure is a property element to refer to a unit of measure. This is an empty element which carries a reference to a unit of measure definition.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("UnitOfMeasureType", Namespace="http://www.opengis.net/gml/3.2")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("unitOfMeasure", Namespace="http://www.opengis.net/gml/3.2")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConversionToPreferredUnitType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DerivationUnitTermType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RoughConversionToPreferredUnit))]
    public partial class UnitOfMeasureType
    {
        
        /// <summary>
        /// <para>The simple type gml:UomIdentifer defines the syntax and value space of the unit of measure identifier.</para>
        /// <para xml:lang="en">Pattern: ([^: \n\r\t]+)|(([a-zA-Z][a-zA-Z0-9\-\+\.]*:|\.\./|\./|#).*).</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([^: \\n\\r\\t]+)|(([a-zA-Z][a-zA-Z0-9\\-\\+\\.]*:|\\.\\./|\\./|#).*)")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("uom")]
        public string Uom { get; set; }
    }
}
